# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a6fdcafbdf7de7ea2a98c72118baada"
name = "25010-proto-nm-app"
application_url = "https://dev.25010-nm.tosho-digital.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dev.25010-nm.tosho-digital.com/auth/callback",
  "https://dev.25010-nm.tosho-digital.com/shopify/callback",
  "https://dev.25010-nm.tosho-digital.com/api/auth/callback",
]
